/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SetupImport } from './routes/setup'
import { Route as LoginImport } from './routes/login'
import { Route as DemoImport } from './routes/demo'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as InvitationSlugImport } from './routes/invitation/$slug'
import { Route as DashboardEditImport } from './routes/dashboard/edit'

// Create/Update Routes

const SetupRoute = SetupImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const InvitationSlugRoute = InvitationSlugImport.update({
  id: '/invitation/$slug',
  path: '/invitation/$slug',
  getParentRoute: () => rootRoute,
} as any)

const DashboardEditRoute = DashboardEditImport.update({
  id: '/dashboard/edit',
  path: '/dashboard/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/edit': {
      id: '/dashboard/edit'
      path: '/dashboard/edit'
      fullPath: '/dashboard/edit'
      preLoaderRoute: typeof DashboardEditImport
      parentRoute: typeof rootRoute
    }
    '/invitation/$slug': {
      id: '/invitation/$slug'
      path: '/invitation/$slug'
      fullPath: '/invitation/$slug'
      preLoaderRoute: typeof InvitationSlugImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/invitation/$slug': typeof InvitationSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/invitation/$slug': typeof InvitationSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/invitation/$slug': typeof InvitationSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/login'
    | '/setup'
    | '/dashboard/edit'
    | '/invitation/$slug'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/login'
    | '/setup'
    | '/dashboard/edit'
    | '/invitation/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/login'
    | '/setup'
    | '/dashboard/edit'
    | '/invitation/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  DashboardEditRoute: typeof DashboardEditRoute
  InvitationSlugRoute: typeof InvitationSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  DashboardEditRoute: DashboardEditRoute,
  InvitationSlugRoute: InvitationSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/demo",
        "/login",
        "/setup",
        "/dashboard/edit",
        "/invitation/$slug",
        "/dashboard/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/demo": {
      "filePath": "demo.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx"
    },
    "/dashboard/edit": {
      "filePath": "dashboard/edit.tsx"
    },
    "/invitation/$slug": {
      "filePath": "invitation/$slug.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
